### ISSUE TITLE
Aspheric with a flat face produces no refraction

### ISSUE THREAD

**Issue by ElliotB256** [bryancole/raypier_optics#19]
Hi bryan,

I was modelling a [ThorLabs A230-A](https://www.thorlabs.com/thorproduct.cfm?partnumber=A230-A) which has a flat face on the back. I wasn't entirely sure the 'correct' way to do this in the API, but I set the curvature to infinite for the back face and at least the graphics plot showed me what I expected:

```
class TL_A230(AsphericLens):
    name = "TL_A230"
    diameter = 6.33
    CT = 2.94 # center thickness
    A_conic = -0.1263039 
    A_curvature = -3.48 # CURV # NOTE THAT CURVATURE IN ZEMAX IS 1/RADIUS, WHEREAS RAYPIER IS RADIUS!
    A4 = 1.2606314E-03
    A6 = 1.0900023E-04 
    A8 = -3.2255631E-07
    A10 = 7.8343862E-07
    A12 = 0
    A14 = 0
    A16 = 0
    B_curvature = np.inf # <-------
    B_conic = 0
    B4 = 0
    B6 = 0
    B8 = 0
    B10 = 0
    B12 = 0
    B14 = 0
    B16 = 0
```

However, doing this means the rays pass through the back face with no refraction whatsoever. No error is thrown:

![image](https://github.com/user-attachments/assets/3b4117e9-b22f-42d9-b1da-b1a7d4035b29)

Compare this to a `B_curvature` value of 1e6:

![image](https://github.com/user-attachments/assets/adbe9474-c31d-4279-b69e-5171cdd18e5b)

So it appears like specifying an infinite value for B_curvature produces a flat surface but silently breaks the refraction. Is this an error? What is the intended way to simulate a flat surface?

Cheers,
Elliot

**Comment by bryancole** [comment]
I'm sorry it's taken me 2.5 months to respond to this. As you have discovered, putting an Inf for the curvature breaks the maths. With hindsight, defining the curvature as "radius of curvature" rather than "1/radius" was a mistake. To achieve a plano-aspheric lens as you describe, you could try making the B_curvature something very large. However, a better approach is to derive a new class which constructs the lens faces as one aspheric face, and one planar-face. I'll try to commit an example later today.

**Comment by bryancole** [comment]
I''ve completed a PlanoAsphericLens class and created a Thorlabs_A230_A lense following your example, as a demo. There is also an example script at examples/aspheric_lens_example.py. This change is pushed both to master and also to the bezier_patches branch which I happen to be working on right now. Hopefully this resolves this particular issue so I'm closing it. Let me know (and reopen) if you spot any problems.

The example script:
`
from raypier.aspherics import Thorlabs_A230_A
from raypier.sources import ParallelRaySource
from raypier.tracer import RayTraceModel
from raypier.results import FocalPoint
from raypier.windows import CircularWindow

lens1 = Thorlabs_A230_A()

win = CircularWindow(centre=(0.,0.,4.0), direction=(0.,0.,1.),
                     thickness=0.25, diameter=5.0)

src = ParallelRaySource(origin=(0.,0.,-10.), 
                        direction=(0.,0.,1.),
                        radius=2.5,
                        rings=7,
                        wavelength=0.78,
                        max_ray_len=20.0,
                        show_normals=True,
                        display="wires",
                        scale_factor=0.02)

focus = FocalPoint(source=src)

model = RayTraceModel(optics=[lens1, win], sources=[src], results=[focus])
model.configure_traits()

"""
In our model the focal point comes out as 5.8mm from origin. 
The PDF datasheet for the A230 optic gives a focal point of 5.85mm.
I'm not sure where the discrepancy comes from.
"""

`

![planoaspheric_example](https://github.com/user-attachments/assets/dd868f30-3394-430a-a386-b4175828ecf7)

**Comment by ElliotB256** [comment]
Hey Bryan, thanks very much!

If the original issue still occurs silently, it may be good to add either a warning or better yet an exception? At least that way if people use radius 'incorrectly' they will know that the results generated are erroneous, at present I only found out because I happened to be using the gui to look at the physical assembly.

Do you have any idea for which part the maths breaks down? Or is it multiple places?

Cheers,
Elliot
