### ISSUE TITLE
michelson_interferometer_example, problem with chaco

### ISSUE THREAD

**Issue by Jonas231** [bryancole/raypier_optics#8]
Hi Bryan,
I tried again the michelson_interferometer_example.py. Now the plotting with chaco does not work anymore.
Some months ago I had tried it and it had worked. The installed version of chaco is 5.0.0. 
Do you have an idea where the error could be located?

Best regards,
Jonas

  File "C:\Users\herbst\raypier_o2\raypier_optics\examples\michelson_interferometer_example.py", line 6, in <module>
    from raypier.intensity_image import IntensityImageView

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\raypier-0.2.3-py3.8-win-amd64.egg\raypier\intensity_image.py", line 4, in <module>
    from chaco.api import GridDataSource, GridMapper, ImageData, Spectral,\

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\chaco\api.py", line 343, in <module>
    from chaco.overlays.api import (

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\chaco\overlays\api.py", line 63, in <module>
    from chaco.overlays.layers.api import (

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\chaco\overlays\layers\api.py", line 11, in <module>
    from .status_layer import ErrorLayer, StatusLayer, WarningLayer

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\chaco\overlays\layers\status_layer.py", line 17, in <module>
    from enable.savage.svg.document import SVGDocument

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\enable\savage\svg\document.py", line 27, in <module>
    from . import css

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\enable\savage\svg\css\__init__.py", line 10, in <module>
    from .transform import transformList

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\enable\savage\svg\css\transform.py", line 18, in <module>
    from enable.savage.svg.pathdata import number, maybeComma

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\enable\savage\svg\pathdata.py", line 117, in <module>
    lineTo = Group(Command("L") + Arguments(coordinatePairSequence))

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\enable\savage\svg\pathdata.py", line 29, in Command
    return CaselessPreservingLiteral(char)

  File "C:\Users\herbst\Anaconda3\envs\myRaypier38\lib\site-packages\enable\savage\svg\pathdata.py", line 43, in __init__
    self.name = "'%s'" % matchString

AttributeError: can't set attribute

**Comment by bryancole** [comment]
Hmmm, I guess something is broken in Chaco 5.0.0. I'm using Chaco
4.8.0. It might be an interaction between Chaco and Enable.I am using
Enable-4.8.1.
I think you should either try to update to a newer Chaco + Enable (I'm
 not sure what's current), or downgrade to 4.8.x.
See below for my full conda env package list.
Bryan
###################################################################### 
(raypier_py38) ***@***.*** raytrace]$ conda list# packages in
environment at /home/bryan/miniconda3/envs/raypier_py38:##
Name                    Version                   Build  Channel_libgcc
_mutex             0.1                 conda_forge    conda-
forge_openmp_mutex             4.5                       1_gnu    conda
-forgealsa-
lib                  1.2.3                h516909a_0    conda-
forgeapptools                  5.1.0              pyh44b312d_0    conda
-forgebackcall                  0.2.0              pyh9f0ad1d_0    cond
a-
forgebackports                 1.0                        py_2    conda
-forgebackports.functools_lru_cache
1.6.4              pyhd8ed1ab_0    conda-
forgebrotli                    1.0.9                h9c3ff4c_4    conda
-forgebzip2                     1.0.8                h7f98852_4    cond
a-forgec-
ares                    1.17.1               h7f98852_1    conda-
forgeca-
certificates           2021.5.30            ha878542_0    conda-
forgecertifi                   2021.5.30        py38h578d9bd_0    conda
-forgechaco                     4.8.0                  4a6683_2    dban
ascloudpickle               1.6.0                      py_0    conda-
forgeconfigobj                 5.0.6                      py_0    conda
-forgecurl                      7.76.1               hea6ffbf_2    cond
a-
forgecython                    0.29.23          py38h709712a_0    conda
-forgedbus                      1.13.6               h48d8840_2    cond
a-
forgedecorator                 5.0.9              pyhd8ed1ab_0    conda
-forgedouble-
conversion         3.1.5                h9c3ff4c_2    conda-
forgeeigen                     3.3.9                h4bd325d_1    conda
-forgeenable                    4.8.1                  b328ed_2    dban
asenvisage                  6.0.0              pyhd8ed1ab_0    conda-
forgeexpat                     2.3.0                h9c3ff4c_0    conda
-forgeffmpeg                    4.3.1                hca11adc_2    cond
a-forgefont-ttf-dejavu-sans-mono
2.37                 hab24e00_0    conda-forgefont-ttf-
inconsolata      3.000                h77eed37_0    conda-forgefont-
ttf-source-code-pro  2.038                h77eed37_0    conda-
forgefont-ttf-
ubuntu           0.83                 hab24e00_0    conda-
forgefontconfig                2.13.1            hba837de_1005    conda
-forgefonts-conda-
ecosystem     1                             0    conda-forgefonts-
conda-forge         1                             0    conda-
forgefonttools                 4.17.1             pyhd8ed1ab_0    conda
-forgefreeimage                 3.18.0               h88c329d_7    cond
a-
forgefreetype                  2.10.4               h0708190_1    conda
-forgegettext                   0.19.8.1          h0b5b191_1005    cond
a-
forgegl2ps                     1.4.2                h0708190_0    conda
-forgeglew                      2.1.0                h9c3ff4c_2    cond
a-
forgeglib                      2.68.2               h9c3ff4c_0    conda
-forgeglib-
tools                2.68.2               h9c3ff4c_0    conda-
forgegmp                       6.2.1                h58526e2_0    conda
-forgegnutls                    3.6.13               h85f3911_1    cond
a-forgegst-plugins-
base          1.18.4               hf529b03_2    conda-
forgegstreamer                 1.18.4               h76c114f_2    conda
-forgehdf4                      4.2.15               h10796ff_3    cond
a-
forgehdf5                      1.10.6          nompi_h6a2412b_1114    c
onda-
forgeicu                       68.1                 h58526e2_0    conda
-forgeilmbase                   2.5.5                h780b84a_0    cond
a-forgeimportlib-
metadata        4.0.1            py38h578d9bd_0    conda-
forgeimportlib_metadata        4.0.1                hd8ed1ab_0    conda
-forgeimportlib_resources       5.1.3            py38h578d9bd_0    cond
a-
forgeipykernel                 5.5.5            py38hd0cf306_0    conda
-forgeipython                   7.24.0           py38hd0cf306_0    cond
a-
forgeipython_genutils          0.2.0                      py_1    conda
-forgejedi                      0.18.0           py38h578d9bd_2    cond
a-
forgejpeg                      9d                   h36c2ea0_0    conda
-forgejsoncpp                   1.9.4                h4bd325d_2    cond
a-
forgejupyter_client            6.1.12             pyhd8ed1ab_0    conda
-forgejupyter_core              4.7.1            py38h578d9bd_0    cond
a-
forgejxrlib                    1.1                  h7f98852_2    conda
-forgekrb5                      1.19.1               hcc1bbae_0    cond
a-
forgelame                      3.100             h7f98852_1001    conda
-forgelcms2                     2.12                 hddcbb42_0    cond
a-forgeld_impl_linux-
64          2.35.1               hea4e1c9_2    conda-
forgelibblas                   3.9.0                9_openblas    conda
-forgelibcblas                  3.9.0                9_openblas    cond
a-
forgelibclang                  11.1.0          default_ha53f305_1    co
nda-
forgelibcurl                   7.76.1               h2574ce0_2    conda
-forgelibedit                   3.1.20191231         he28a2e2_2    cond
a-
forgelibev                     4.33                 h516909a_1    conda
-forgelibevent                  2.1.10               hcdb4288_3    cond
a-
forgelibffi                    3.3                  h58526e2_2    conda
-forgelibgcc-
ng                 9.3.0               h2828fa1_19    conda-
forgelibgfortran-
ng            9.3.0               hff62375_19    conda-
forgelibgfortran5              9.3.0               hff62375_19    conda
-forgelibglib                   2.68.2               h3e27bee_0    cond
a-
forgelibglu                    9.0.0             he1b5a44_1001    conda
-forgelibgomp                   9.3.0               h2828fa1_19    cond
a-
forgelibiconv                  1.16                 h516909a_0    conda
-forgeliblapack                 3.9.0                9_openblas    cond
a-
forgelibllvm11                 11.1.0               hf817b99_2    conda
-forgelibnetcdf                 4.8.0           nompi_hcd642e3_103    c
onda-
forgelibnghttp2                1.43.0               h812cca2_0    conda
-forgelibogg                    1.3.4                h7f98852_1    cond
a-
forgelibopenblas               0.3.15          pthreads_h8fe5266_1    c
onda-
forgelibopus                   1.3.1                h7f98852_1    conda
-forgelibpng                    1.6.37               h21135ba_2    cond
a-
forgelibpq                     13.3                 hd57d9b9_0    conda
-forgelibraw                    0.20.2               h10796ff_1    cond
a-
forgelibsodium                 1.0.18               h36c2ea0_1    conda
-forgelibssh2                   1.9.0                ha56f1ee_6    cond
a-forgelibstdcxx-
ng              9.3.0               h6de172a_19    conda-
forgelibtheora                 1.1.1             h7f98852_1005    conda
-forgelibtiff                   4.2.0                hbd63e13_2    cond
a-
forgelibuuid                   2.32.1            h7f98852_1000    conda
-forgelibvorbis                 1.3.7                h9c3ff4c_0    cond
a-forgelibwebp-
base              1.2.0                h7f98852_2    conda-
forgelibxcb                    1.13              h7f98852_1003    conda
-forgelibxkbcommon              1.0.3                he3ba5ed_0    cond
a-
forgelibxml2                   2.9.12               h72842e0_0    conda
-forgelibzip                    1.7.3                h4de3113_0    cond
a-
forgeloguru                    0.5.3            py38h578d9bd_2    conda
-forgelz4-
c                     1.9.3                h9c3ff4c_0    conda-
forgematplotlib-
inline         0.1.2              pyhd8ed1ab_2    conda-
forgemayavi                    4.7.2            py38h32b5f5e_4    conda
-forgemunkres                   1.1.4              pyh9f0ad1d_0    cond
a-forgemysql-
common              8.0.23               ha770c72_2    conda-
forgemysql-
libs                8.0.23               h935591d_2    conda-
forgencurses                   6.2                  h58526e2_4    conda
-forgenettle                    3.6                  he412f7d_0    cond
a-
forgenspr                      4.30                 h9c3ff4c_0    conda
-forgenss                       3.65                 hb5efdd6_0    cond
a-
forgenumpy                     1.20.3           py38h9894fe3_0    conda
-forgeocct                      7.5.2                h7391655_0    cond
a-
forgeolefile                   0.46               pyh9f0ad1d_1    conda
-forgeopenexr                   2.5.5                hf817b99_0    cond
a-
forgeopenh264                  2.1.1                h780b84a_0    conda
-forgeopenjpeg                  2.4.0                hb52868f_1    cond
a-
forgeopenssl                   1.1.1k               h7f98852_0    conda
-forgeparso                     0.8.2              pyhd8ed1ab_0    cond
a-
forgepcre                      8.44                 he1b5a44_0    conda
-forgepexpect                   4.8.0              pyh9f0ad1d_2    cond
a-
forgepickleshare               0.7.5                   py_1003    conda
-forgepillow                    8.2.0            py38ha0e1e83_1    cond
a-
forgepip                       21.1.1             pyhd8ed1ab_0    conda
-forgeproj                      7.2.0                h277dcde_2    cond
a-forgeprompt-
toolkit            3.0.18             pyha770c72_0    conda-
forgepthread-
stubs             0.4               h36c2ea0_1001    conda-
forgeptyprocess                0.7.0              pyhd3deb0d_0    conda
-forgepugixml                   1.11.4               h9c3ff4c_0    cond
a-
forgepyface                    7.3.0              pyh44b312d_1    conda
-forgepygments                  2.9.0              pyhd8ed1ab_0    cond
a-
forgepyparsing                 2.4.7              pyh9f0ad1d_0    conda
-forgepyqt                      5.12.3           py38h578d9bd_7    cond
a-forgepyqt-
impl                 5.12.3           py38h7400c14_7    conda-
forgepyqt5-
sip                 4.19.18          py38h709712a_7    conda-
forgepyqtchart                 5.12             py38h7400c14_7    conda
-forgepyqtwebengine             5.12.1           py38h7400c14_7    cond
a-
forgepython                    3.8.10          h49503c6_1_cpython    co
nda-forgepython-
dateutil           2.8.1                      py_0    conda-
forgepython_abi                3.8                      1_cp38    conda
-forgepythonocc-
core            7.5.1            py38hb1953e2_0    conda-
forgepyyaml                    5.4.1            py38h497a2fe_0    conda
-forgepyzmq                     22.1.0           py38h2035c66_0    cond
a-
forgeqt                        5.12.9               hda022c4_4    conda
-forgerapidjson                 1.1.0             he1b5a44_1002    cond
a-
forgereadline                  8.1                  h46c0cb4_0    conda
-forgescipy                     1.6.3            py38h7b17777_0    cond
a-
forgesetuptools                49.6.0           py38h578d9bd_3    conda
-forgesix                       1.16.0             pyh6c4a22f_0    cond
a-forgespyder-
kernels            2.0.3            py38h578d9bd_0    conda-
forgesqlite                    3.35.5               h74cdb3f_0    conda
-forgetbb                       2020.2               h4bd325d_4    cond
a-forgetbb-
devel                 2020.2               h4bd325d_4    conda-
forgetk                        8.6.10               h21135ba_1    conda
-forgetornado                   6.1              py38h497a2fe_1    cond
a-
forgetraitlets                 5.0.5                      py_0    conda
-forgetraits                    6.2.0            py38h497a2fe_0    cond
a-
forgetraitsui                  7.2.0              pyhd8ed1ab_0    conda
-forgeunicodedata2              13.0.0.post2     py38h1e0a361_1    cond
a-
forgeutfcpp                    3.2                  ha770c72_0    conda
-forgevtk                       9.0.1           no_osmesa_py38h3850a3d_
109    conda-
forgewcwidth                   0.2.5              pyh9f0ad1d_2    conda
-forgewheel                     0.36.2             pyhd3deb0d_0    cond
a-
forgewurlitzer                 2.1.0            py38h578d9bd_0    conda
-forgex264                      1!161.3030           h7f98852_0    cond
a-forgexorg-
kbproto              1.0.7             h7f98852_1002    conda-
forgexorg-
libice               1.0.10               h7f98852_0    conda-
forgexorg-
libsm                1.2.3             hd9c2040_1000    conda-
forgexorg-
libx11               1.7.1                h7f98852_0    conda-
forgexorg-
libxau               1.0.9                h7f98852_0    conda-
forgexorg-
libxdmcp             1.1.3                h7f98852_0    conda-
forgexorg-
libxext              1.3.4                h7f98852_1    conda-
forgexorg-
libxt                1.2.1                h7f98852_2    conda-
forgexorg-
xextproto            7.3.0             h7f98852_1002    conda-
forgexorg-
xproto               7.0.31            h7f98852_1007    conda-
forgexz                        5.2.5                h516909a_1    conda
-forgeyaml                      0.2.5                h516909a_0    cond
a-
forgezeromq                    4.3.4                h9c3ff4c_0    conda
-forgezipp                      3.4.1              pyhd8ed1ab_0    cond
a-
forgezlib                      1.2.11            h516909a_1010    conda
-forgezstd                      1.4.9                ha95c52a_0    cond
a-forge
